In [2]:
#import required libraries
import os
import pandas as pd
import numpy as np

#find the current directory
current_directory = os.getcwd()

#moves up one folder in the file directory (in order to get to the input folder)
path_parent = os.path.dirname(current_directory)

'''
Note about the data:
The folder name for the original data files is "Input", which contains the following files:
1. PSC_data_trimmed.csv: data file containing just the subset of 50 variables
2. Main.csv = the original, ~ 2 million entry dataset 
3. Columns.csv = a datafile containing the subset of columns from the original dataset that 
we want to use
testing testing
'''
#joins the file path together and reads in the data frame
#psc_trimmed = pd.read_csv(os.path.join(path_parent, "Input", "PSC_data_trimmed.csv"))

'\nNote about the data:\nThe folder name for the original data files is "Input", which contains the following files:\n1. PSC_data_trimmed.csv: data file containing just the subset of 50 variables\n2. Main.csv = the original, ~ 2 million entry dataset \n3. Columns.csv = a datafile containing the subset of columns from the original dataset that \nwe want to use\ntesting testing\n'

In [5]:
#examine the dataset 
psc_trimmed.head()

,Unnamed: 0,JPR_ID,OFF_SEX,OFF_RACE,dofage,otn,OFN_TITLE,OFN_COUNT,OFN_LABEL,OFN_GRADE,...,id_variable,PCS_OFF_ID,conform,OFF_CRIMEFREE,SGR_LVL_OGS_PRS,DOB2,MS_OFFBODY,MS_SENTJP,JP_CC_BUG,ofn_label
0,1,640001,F,White,36.689938,H182628-5,18,1,Corruption of Minors - when of a sexual nature,M-1,...,1904581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2,642480,M,White,18.540726,0,75,1,DUI - M-2,M-2,...,1157226,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3,660434,M,White,36.914442,H3618344,75,1,DUI - M-2,M-2,...,1467650,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4,628940,M,Black,22.297057,G0816126,18,1,Simple Assault,M-2,...,1746031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5,594048,M,White,40.087611,H240127-6,75,1,DUI - M-1,M-1,...,1374131,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN